name: road_damage_env
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - pillow
  - scikit-learn
  - pyyaml
  - tqdm
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==2.4.1+cpu
      - torchvision==0.19.1+cpu
      - ultralytics==8.3.0
      - huggingface-hub==0.26.2

   
